# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-demo',
                'doc_host': 'https://thecharlieblake.github.io',
                'git_url': 'https://github.com/thecharlieblake/nbdev-demo',
                'lib_path': 'nbdev_demo'},
  'syms': { 'nbdev_demo.cbdemo': { 'nbdev_demo.cbdemo.foo': ( 'https://thecharlieblake.github.io/cbdemo.html#foo',
                                                              'https://github.com/thecharlieblake/nbdev-demo/blob/master/nbdev_demo/cbdemo.py#L7'),
                                   'nbdev_demo.cbdemo.say_hello': ( 'https://thecharlieblake.github.io/cbdemo.html#say_hello',
                                                                    'https://github.com/thecharlieblake/nbdev-demo/blob/master/nbdev_demo/cbdemo.py#L10')},
            'nbdev_demo.core': { 'nbdev_demo.core.foo': ( 'https://thecharlieblake.github.io/core.html#foo',
                                                          'https://github.com/thecharlieblake/nbdev-demo/blob/master/nbdev_demo/core.py#L7')}}}