# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-demo',
                'doc_host': 'https://thecharlieblake.github.io',
                'git_url': 'https://github.com/thecharlieblake/nbdev-demo',
                'lib_path': 'nbdev_demo'},
  'syms': { 'nbdev_demo.core': { 'nbdev_demo.core.foo': ( 'https://thecharlieblake.github.io/core.html#foo',
                                                          'https://github.com/thecharlieblake/nbdev-demo/blob/master/nbdev_demo/core.py#L7')}}}